spring.application.name=smartfoodfitness
spring.datasource.url=jdbc:postgresql://localhost:5432/smartFoodFitnessDB
spring.datasource.username=smartFoodFitnessUser
spring.datasource.password=User123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
app.jwt.secret=CHANGE_ME_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS
app.jwt.expirationSeconds=604800


usda.fdc.apiKey=Xi06mrbopApZdAtKTCVQDgFLBpOoQr2Ur9Y9p6qn

# WGER
wger.base-url=https://wger.de/api/v2
wger.api-key=38cd57f9c6a2d86b85d444df983b075d45740cec
wger.language-id=2
# WGER category mapping rules (comma-separated keywords)
wger.map.chest=pector,pec,bench,fly
wger.map.back=lat,back,row,pull,deadlift
wger.map.shoulders=deltoid,shoulder,overhead,lateral raise
wger.map.arms=bicep,tricep,curl,dip,forearm
wger.map.core=abs,core,oblique,plank,crunch
wger.map.legs=quad,hamstring,glute,calf,squat,lunge,leg
wger.map.cardio=cardio,run,running,bike,rowing,burpee,jump,sprint
