spring.application.name=smartfoodfitness

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/smartFoodFitnessDB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:smartFoodFitnessUser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:User123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}

server.forward-headers-strategy=native

app.jwt.secret=${APP_JWT_SECRET:iGKqrlrFbQD29cTip09LeU1rjyQ8fO9X}
app.jwt.expirationSeconds=${APP_JWT_EXPIRATION_SECONDS:604800}


usda.fdc.apiKey=${USDA_API_KEY:Xi06mrbopApZdAtKTCVQDgFLBpOoQr2Ur9Y9p6qn}

wger.base-url=${WGER_BASE_URL:https://wger.de/api/v2}
wger.api-key=${WGER_API_KEY:38cd57f9c6a2d86b85d444df983b075d45740cec}
wger.language-id=${WGER_LANGUAGE_ID:2}

wger.map.chest=${WGER_MAP_CHEST:pector,pec,bench,fly}
wger.map.back=${WGER_MAP_BACK:lat,back,row,pull,deadlift}
wger.map.shoulders=${WGER_MAP_SHOULDERS:deltoid,shoulder,overhead,lateral raise}
wger.map.arms=${WGER_MAP_ARMS:bicep,tricep,curl,dip,forearm}
wger.map.core=${WGER_MAP_CORE:abs,core,oblique,plank,crunch}
wger.map.legs=${WGER_MAP_LEGS:quad,hamstring,glute,calf,squat,lunge,leg}
wger.map.cardio=${WGER_MAP_CARDIO:cardio,run,running,bike,rowing,burpee,jump,sprint}
